Tracker:AddLocations("locations/Arichs Ambush.json")
Tracker:AddLocations("locations/Banana Bird.json")
Tracker:AddLocations("locations/Barboss Barrier.json")
Tracker:AddLocations("locations/Barrel Drop Bounce.json")
Tracker:AddLocations("locations/Barrel Shield Bust-Up.json")
Tracker:AddLocations("locations/Bazzas Blockade.json")
Tracker:AddLocations("locations/Belchas Barn.json")
Tracker:AddLocations("locations/Blazing Bazukas.json")
Tracker:AddLocations("locations/Bleaks House.json")
Tracker:AddLocations("locations/Bobbing Barrel Brawl.json")
Tracker:AddLocations("locations/Buzzer Barrage.json")
Tracker:AddLocations("locations/Creepy Caverns.json")
Tracker:AddLocations("locations/Criss Kross Cliffs.json")
Tracker:AddLocations("locations/Demolition Drain-Pipe.json")
Tracker:AddLocations("locations/Doorstop Dash.json")
Tracker:AddLocations("locations/Fire-Ball Frenzy.json")
Tracker:AddLocations("locations/Fish Food Frenzy.json")
Tracker:AddLocations("locations/Floodlit Fish.json")
Tracker:AddLocations("locations/KAOS Karnage.json")
Tracker:AddLocations("locations/Koindozer Klamber.json")
Tracker:AddLocations("locations/Kong-Fused Cliffs.json")
Tracker:AddLocations("locations/Konveyor Rope Klash.json")
Tracker:AddLocations("locations/Krackshot Krock.json")
Tracker:AddLocations("locations/Kreeping Klasps.json")
Tracker:AddLocations("locations/Krevice Kreepers.json")
Tracker:AddLocations("locations/Lakeside Limbo.json")
Tracker:AddLocations("locations/Lemguin Lunge.json")
Tracker:AddLocations("locations/Lightning Look-Out.json")
Tracker:AddLocations("locations/Low-G Labyrinth.json")
Tracker:AddLocations("locations/Murky Mill.json")
Tracker:AddLocations("locations/Poisonous Pipeline.json")
Tracker:AddLocations("locations/Pot Hole Panic.json")
Tracker:AddLocations("locations/Ripsaw Rage.json")
Tracker:AddLocations("locations/Riverside Race.json")
Tracker:AddLocations("locations/Rocket Barrel Ride.json")
Tracker:AddLocations("locations/Rocket Rush.json")
Tracker:AddLocations("locations/Ropey Rumpus.json")
Tracker:AddLocations("locations/Skiddas Row.json")
Tracker:AddLocations("locations/Springin Spiders.json")
Tracker:AddLocations("locations/Squeals on Wheels.json")
Tracker:AddLocations("locations/Squirts Showdown.json")
Tracker:AddLocations("locations/Stampede Sprint.json")
Tracker:AddLocations("locations/Swoopy Salvo.json")
Tracker:AddLocations("locations/Tearaway Toboggan.json")
Tracker:AddLocations("locations/Tidal Trouble.json")
Tracker:AddLocations("locations/Tracker Barrel Trek.json")
Tracker:AddLocations("locations/Tyrant Twin Tussle.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/World Map.json")
